apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
spec:
  params:
    - name: run-image
      value: harbor.terasky.demo/tap-apps/tanzu-java-web-app
    - name: tekton-pipeline-name
      value: developer-defined-tekton-pipeline
  source:
    git:
      url: https://github.com/sample-accelerators/tanzu-java-web-app
      ref:
        branch: main
